parameters: {}
environment: {}
packages:
    - name: cron
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: texts
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          websecure: false
          parameters: {}
          environment: 
            name: "${name}"
          annotations: {}
          limits: {}
